# <b> Evaluatie transcriptie en sprekerdiarisatie van het Medium Whisper model </b>

Geteste modellen:
- medium
- large-v3 alleen bij twijfel / als referentie

Per fragment vergelijk ik:
1. handmatige referentietranscriptie
2. output van Whisper
3. opvallende fouten
4. mogelijke impact op didactische analyse

## 1. Functies

#### 1.1. Bestanden laden

In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display, HTML
import html


def load_diarized_json(path):
    path = Path(path)

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    return pd.DataFrame(data["segments"]), data


def load_manual_transcript(path):
    path = Path(path)

    lines = [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]

    data = []

    for line in lines:
        if ":" not in line:
            continue

        speaker, text = line.split(":", 1)

        data.append({
            "speaker": speaker.strip(),
            "text": text.strip().strip('"')
        })

    return pd.DataFrame(data)

#### 1.2. Vergelijken van transcripties

In [2]:
def show_transcription_comparison(
    df,
    manual_df,
    start_time,
    end_time,
    title="Handmatige transcriptie vs. Whisper"
):
    fragment = df[
        (df["end"] >= start_time) &
        (df["start"] <= end_time)
    ].copy()

    manual_text = "\n\n".join(manual_df["text"].tolist())
    whisper_text = "\n\n".join(fragment["text"].tolist())

    display(HTML(f"""
    <h3>{title}</h3>

    <table style="width:100%; table-layout:fixed; border-collapse:collapse;">
        <tr>
            <th style="width:50%; text-align:left; padding:10px; border:1px solid #ccc;">
                Handmatig
            </th>
            <th style="width:50%; text-align:left; padding:10px; border:1px solid #ccc;">
                Whisper
            </th>
        </tr>
        <tr>
            <td style="vertical-align:top; padding:12px; border:1px solid #ccc; white-space:pre-wrap;">
                {html.escape(manual_text)}
            </td>
            <td style="vertical-align:top; padding:12px; border:1px solid #ccc; white-space:pre-wrap;">
                {html.escape(whisper_text)}
            </td>
        </tr>
    </table>
    """))

    return fragment

#### 1.3. Vergelijken van sprekerdiarisatie

In [3]:
def show_diarization_comparison(
    df,
    manual_df,
    start_time,
    end_time
):
    fragment = df[
        (df["end"] >= start_time) &
        (df["start"] <= end_time)
    ].copy()

    manual_text = "\n\n".join(
        f"{row['speaker']}: {row['text']}"
        for _, row in manual_df.iterrows()
    )

    diarization_text = "\n\n".join(
        f"[{row['start']:.1f}-{row['end']:.1f}] "
        f"{row['speaker']}: {row['text']}"
        for _, row in fragment.iterrows()
    )

    display(HTML(f"""
    <h3>Handmatige sprekerverdeling vs. diarization</h3>

    <table style="width:100%; table-layout:fixed; border-collapse:collapse;">
        <tr>
            <th style="width:50%; text-align:left; padding:10px; border:1px solid #ccc;">
                Handmatig
            </th>
            <th style="width:50%; text-align:left; padding:10px; border:1px solid #ccc;">
                Diarization
            </th>
        </tr>
        <tr>
            <td style="vertical-align:top; padding:12px; border:1px solid #ccc; white-space:pre-wrap;">
                {html.escape(manual_text)}
            </td>
            <td style="vertical-align:top; padding:12px; border:1px solid #ccc; white-space:pre-wrap;">
                {html.escape(diarization_text)}
            </td>
        </tr>
    </table>
    """))

    details = fragment[
        [
            "start",
            "end",
            "speaker",
            "text",
            "speaker_confidence",
            "overlap",
            "uncertain_assignment"
        ]
    ].copy()

    details["start"] = details["start"].round(1)
    details["end"] = details["end"].round(1)
    details["speaker_confidence"] = details["speaker_confidence"].round(2)

    display(details)

    return fragment

## <b> 2. Fragment 1 — rumoer + overlap </b>

Duur: 45 sec  
Model: medium  
Bestand: `testaudio1_fragment.mp3`

## 2.1. Handmatige transcriptie versus Whisper transcriptie

In [4]:
df1, data1 = load_diarized_json(
    "../../Data-local/processed/diarization/testaudio1_fragment_diarized.json"
)

manual1 = load_manual_transcript(
    "../../Data-local/raw/testaudio1_manual.txt"
)

show_transcription_comparison(
    df1,
    manual1,
    start_time=5,
    end_time=21
)

,start,end,speaker,text,avg_logprob,no_speech_prob,compression_ratio,quality_flags,speaker_raw,speaker_confidence,overlap,uncertain_assignment
2,4.12,9.36,MAIN_SPEAKER,"Oké, heel mooi.",-0.42402,0.067625,1.470588,[],SPEAKER_01,0.5615,True,True
3,9.52,11.64,MAIN_SPEAKER,Dit ben jij. Dit ben ik.,-0.42402,0.067625,1.470588,[],SPEAKER_01,0.7377,True,False
4,11.80,15.64,MAIN_SPEAKER,Zit er ook nog in je karaktereigenschap iets m...,-0.42402,0.067625,1.470588,[],SPEAKER_01,0.9010,False,False
5,15.80,20.28,MAIN_SPEAKER,Nee. Dit is een heel originele manier om te la...,-0.42402,0.067625,1.470588,[],SPEAKER_01,1.0000,False,False
6,20.44,24.48,OTHER_SPEAKER_1,Er zitten alle ingrediënten in. Wie wil er nog...,-0.42402,0.067625,1.470588,[],SPEAKER_00,0.5329,True,True

### 2.1. Conclusie transcriptie

De transcriptie met Whisper Medium behoudt de inhoud van het gesprek grotendeels correct. 
Enkele korte leerlingreacties worden samengevoegd met docenttekst of niet afzonderlijk weergegeven. 
Ook wijkt de formulering op sommige plekken licht af van de handmatige transcriptie, zonder dat de hoofdboodschap verloren gaat.

Voor analyse van docentgedrag lijkt deze transcriptkwaliteit voorlopig bruikbaar. 
Voor indicatoren die afhankelijk zijn van korte leerlingreacties of exacte interactievolgorde blijft extra voorzichtigheid nodig.

## 2.2. Sprekerdiarisatie-evaluatie

In [5]:
show_diarization_comparison(
    df1,
    manual1,
    start_time=5,
    end_time=21
)

,start,end,speaker,text,speaker_confidence,overlap,uncertain_assignment
2,4.1,9.4,MAIN_SPEAKER,"Oké, heel mooi.",0.56,True,True
3,9.5,11.6,MAIN_SPEAKER,Dit ben jij. Dit ben ik.,0.74,True,False
4,11.8,15.6,MAIN_SPEAKER,Zit er ook nog in je karaktereigenschap iets m...,0.90,False,False
5,15.8,20.3,MAIN_SPEAKER,Nee. Dit is een heel originele manier om te la...,1.00,False,False
6,20.4,24.5,OTHER_SPEAKER_1,Er zitten alle ingrediënten in. Wie wil er nog...,0.53,True,True

,start,end,speaker,text,avg_logprob,no_speech_prob,compression_ratio,quality_flags,speaker_raw,speaker_confidence,overlap,uncertain_assignment
2,4.12,9.36,MAIN_SPEAKER,"Oké, heel mooi.",-0.42402,0.067625,1.470588,[],SPEAKER_01,0.5615,True,True
3,9.52,11.64,MAIN_SPEAKER,Dit ben jij. Dit ben ik.,-0.42402,0.067625,1.470588,[],SPEAKER_01,0.7377,True,False
4,11.80,15.64,MAIN_SPEAKER,Zit er ook nog in je karaktereigenschap iets m...,-0.42402,0.067625,1.470588,[],SPEAKER_01,0.9010,False,False
5,15.80,20.28,MAIN_SPEAKER,Nee. Dit is een heel originele manier om te la...,-0.42402,0.067625,1.470588,[],SPEAKER_01,1.0000,False,False
6,20.44,24.48,OTHER_SPEAKER_1,Er zitten alle ingrediënten in. Wie wil er nog...,-0.42402,0.067625,1.470588,[],SPEAKER_00,0.5329,True,True

### 2.2.1. Diarization conclusie

De diarization herkent de hoofdspreker in delen van het fragment goed, maar korte wisselingen tussen docent en leerling worden niet betrouwbaar gescheiden. Een belangrijke oorzaak is dat sommige Whisper-segmenten al tekst van meerdere sprekers bevatten. Omdat de huidige pipeline één sprekerlabel per Whisper-segment toekent, kan een korte leerlingreactie daardoor aan de docent worden gekoppeld of andersom.  
De diarization is daarom bruikbaar om langere spreekbeurten en de dominante spreker te onderscheiden, maar minder betrouwbaar voor zeer korte interacties en snelle sprekerwisselingen. Dit wordt als beperking meegenomen in de latere classificatie.

## <b> 3. Fragment 2 — rumoer + overlap </b>

Duur: 45 sec  
Model: medium  
Bestand: `testaudio2_fragment.mp3`

## 3.1. Handmatige transcriptie versus Whisper transcriptie

In [6]:
df2, data2 = load_diarized_json(
    "../../Data-local/processed/diarization/testaudio2_fragment_diarized.json"
)

manual2 = load_manual_transcript(
    "../../Data-local/raw/testaudio2_manual.txt"
)

show_transcription_comparison(
    df2,
    manual2,
    start_time=0,
    end_time=30
)

,start,end,speaker,text,avg_logprob,no_speech_prob,compression_ratio,quality_flags,speaker_raw,speaker_confidence,overlap,uncertain_assignment
0,0.0,2.0,MAIN_SPEAKER,"Vier, Rick. Zegt u het maar.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
1,2.0,4.0,MAIN_SPEAKER,"Ja, kijk maar even in je schrift op de vier.",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.7338,True,False
2,4.0,5.0,MAIN_SPEAKER,Ruud heeft een brommer.,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
3,5.0,7.0,MAIN_SPEAKER,"De tekst gaat toch niet over brommer, of wel?",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
4,7.0,9.0,MAIN_SPEAKER,"Nee, maar het gaat ook niet om de brommer.",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.7548,True,False
5,9.0,11.0,MAIN_SPEAKER,"Maar Ruud heeft een probleem, dat is de vraag.",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.6511,True,False
6,11.0,13.0,MAIN_SPEAKER,Wat voor probleem heeft-ie?,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
7,13.0,14.0,MAIN_SPEAKER,Met zijn vrouw.,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
8,14.0,15.0,MAIN_SPEAKER,"Nee, klopt niet.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
9,15.0,16.0,MAIN_SPEAKER,"Ik bedoel, met zijn hond.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
10,16.0,17.0,MAIN_SPEAKER,"Ja, je bent gewoon verzinnen, of niet?",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
11,17.0,18.0,MAIN_SPEAKER,Nee.,-0.230623,0.074439,1.852201,[],SPEAKER_00,0.6366,True,False
12,18.0,19.0,MAIN_SPEAKER,Jawel.,-0.230623,0.074439,1.852201,[],SPEAKER_00,0.9759,False,False
13,19.0,20.0,MAIN_SPEAKER,Dan staat-ie echt waar.,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
14,20.0,21.0,MAIN_SPEAKER,"Ja, het staat in jouw schrift.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
15,21.0,23.0,MAIN_SPEAKER,"Misschien staat het niet in zijn schrift, miss...",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.8802,False,False
16,23.0,25.0,MAIN_SPEAKER,Je ziet je ogen heen en weer gaan.,-0.230623,0.074439,1.852201,[],SPEAKER_00,0.7727,True,False
17,25.0,28.0,MAIN_SPEAKER,"Dus ik denk, nou gaat je hoofd heen en weer.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
18,28.0,30.0,MAIN_SPEAKER,"Dus ja, ja.",-0.543868,0.947564,0.578947,[high_no_speech_prob],SPEAKER_00,1.0000,False,False

### 3.1.1. Conclusie transcriptie

Whisper Medium presteert in dit fragment goed. De inhoud en volgorde van het gesprek worden grotendeels correct weergegeven en zowel de vragen van de docent als de antwoorden van de leerling blijven inhoudelijk herkenbaar. Er zijn kleine verschillen in formulering, maar deze veranderen de betekenis nauwelijks.  
Voor didactische analyse is deze transcriptkwaliteit voldoende om bijvoorbeeld vraaggedrag, uitleg en inhoudelijke reacties van de docent te herkennen.

## 3.2. Diarization-evaluatie

In [7]:
show_diarization_comparison(
    df2,
    manual2,
    start_time=0,
    end_time=30
)

,start,end,speaker,text,speaker_confidence,overlap,uncertain_assignment
0,0.0,2.0,MAIN_SPEAKER,"Vier, Rick. Zegt u het maar.",1.00,False,False
1,2.0,4.0,MAIN_SPEAKER,"Ja, kijk maar even in je schrift op de vier.",0.73,True,False
2,4.0,5.0,MAIN_SPEAKER,Ruud heeft een brommer.,1.00,False,False
3,5.0,7.0,MAIN_SPEAKER,"De tekst gaat toch niet over brommer, of wel?",1.00,False,False
4,7.0,9.0,MAIN_SPEAKER,"Nee, maar het gaat ook niet om de brommer.",0.75,True,False
5,9.0,11.0,MAIN_SPEAKER,"Maar Ruud heeft een probleem, dat is de vraag.",0.65,True,False
6,11.0,13.0,MAIN_SPEAKER,Wat voor probleem heeft-ie?,1.00,False,False
7,13.0,14.0,MAIN_SPEAKER,Met zijn vrouw.,1.00,False,False
8,14.0,15.0,MAIN_SPEAKER,"Nee, klopt niet.",1.00,False,False
9,15.0,16.0,MAIN_SPEAKER,"Ik bedoel, met zijn hond.",1.00,False,False
10,16.0,17.0,MAIN_SPEAKER,"Ja, je bent gewoon verzinnen, of niet?",1.00,False,False
11,17.0,18.0,MAIN_SPEAKER,Nee.,0.64,True,False
12,18.0,19.0,MAIN_SPEAKER,Jawel.,0.98,False,False
13,19.0,20.0,MAIN_SPEAKER,Dan staat-ie echt waar.,1.00,False,False
14,20.0,21.0,MAIN_SPEAKER,"Ja, het staat in jouw schrift.",1.00,False,False
15,21.0,23.0,MAIN_SPEAKER,"Misschien staat het niet in zijn schrift, miss...",0.88,False,False
16,23.0,25.0,MAIN_SPEAKER,Je ziet je ogen heen en weer gaan.,0.77,True,False
17,25.0,28.0,MAIN_SPEAKER,"Dus ik denk, nou gaat je hoofd heen en weer.",1.00,False,False
18,28.0,30.0,MAIN_SPEAKER,"Dus ja, ja.",1.00,False,False

,start,end,speaker,text,avg_logprob,no_speech_prob,compression_ratio,quality_flags,speaker_raw,speaker_confidence,overlap,uncertain_assignment
0,0.0,2.0,MAIN_SPEAKER,"Vier, Rick. Zegt u het maar.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
1,2.0,4.0,MAIN_SPEAKER,"Ja, kijk maar even in je schrift op de vier.",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.7338,True,False
2,4.0,5.0,MAIN_SPEAKER,Ruud heeft een brommer.,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
3,5.0,7.0,MAIN_SPEAKER,"De tekst gaat toch niet over brommer, of wel?",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
4,7.0,9.0,MAIN_SPEAKER,"Nee, maar het gaat ook niet om de brommer.",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.7548,True,False
5,9.0,11.0,MAIN_SPEAKER,"Maar Ruud heeft een probleem, dat is de vraag.",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.6511,True,False
6,11.0,13.0,MAIN_SPEAKER,Wat voor probleem heeft-ie?,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
7,13.0,14.0,MAIN_SPEAKER,Met zijn vrouw.,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
8,14.0,15.0,MAIN_SPEAKER,"Nee, klopt niet.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
9,15.0,16.0,MAIN_SPEAKER,"Ik bedoel, met zijn hond.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
10,16.0,17.0,MAIN_SPEAKER,"Ja, je bent gewoon verzinnen, of niet?",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
11,17.0,18.0,MAIN_SPEAKER,Nee.,-0.230623,0.074439,1.852201,[],SPEAKER_00,0.6366,True,False
12,18.0,19.0,MAIN_SPEAKER,Jawel.,-0.230623,0.074439,1.852201,[],SPEAKER_00,0.9759,False,False
13,19.0,20.0,MAIN_SPEAKER,Dan staat-ie echt waar.,-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
14,20.0,21.0,MAIN_SPEAKER,"Ja, het staat in jouw schrift.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
15,21.0,23.0,MAIN_SPEAKER,"Misschien staat het niet in zijn schrift, miss...",-0.230623,0.074439,1.852201,[],SPEAKER_00,0.8802,False,False
16,23.0,25.0,MAIN_SPEAKER,Je ziet je ogen heen en weer gaan.,-0.230623,0.074439,1.852201,[],SPEAKER_00,0.7727,True,False
17,25.0,28.0,MAIN_SPEAKER,"Dus ik denk, nou gaat je hoofd heen en weer.",-0.230623,0.074439,1.852201,[],SPEAKER_00,1.0000,False,False
18,28.0,30.0,MAIN_SPEAKER,"Dus ja, ja.",-0.543868,0.947564,0.578947,[high_no_speech_prob],SPEAKER_00,1.0000,False,False

### 3.2.1. Diarization conclusie

De diarization is in dit fragment onvoldoende voor betrouwbare sprekerverdeling. Hoewel de handmatige transcriptie duidelijke wisselingen tussen docent en leerling bevat, worden vrijwel alle transcriptsegmenten als MAIN_SPEAKER geclassificeerd.  
Dit betekent dat de tekstinhoud bruikbaar is, maar dat niet betrouwbaar kan worden aangenomen dat iedere als MAIN_SPEAKER gelabelde uitspraak daadwerkelijk van de docent afkomstig is. Voor analyses die alleen naar de inhoud van langere docentpassages kijken kan het fragment nog bruikbaar zijn, maar tellingen van docent- versus leerlinginteractie zouden hierdoor vertekend kunnen worden.

## <b> 4. Fragment 3 — meerdere sprekers + rumoer </b>

Duur: 46 sec  
Model: medium  
Bestand: `testaudio5_fragment.mp3`

## 4.1. Handmatige transcriptie versus Whisper transcriptie

In [8]:
df3, data3 = load_diarized_json(
    "../../Data-local/processed/diarization/testaudio5_fragment_diarized.json"
)

manual3 = load_manual_transcript(
    "../../Data-local/raw/testaudio5_manual.txt"
)

show_transcription_comparison(
    df3,
    manual3,
    start_time=0,
    end_time=46
)

,start,end,speaker,text,avg_logprob,no_speech_prob,compression_ratio,quality_flags,speaker_raw,speaker_confidence,overlap,uncertain_assignment
0,0.82,3.26,MAIN_SPEAKER,"Oswaldo is jouw beste vriend, hè? Of niet?",-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
1,3.38,4.38,MAIN_SPEAKER,"Hier in de klas, ja.",-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
2,4.50,8.98,MAIN_SPEAKER,Stel je nou voor dat Oswaldo homo is.,-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
3,9.10,10.82,MAIN_SPEAKER,Zou dat invloed hebben op je vriendschap?,-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
4,10.94,12.54,MAIN_SPEAKER,Jazeker. Dat zou wel invloed hebben.,-0.33186,0.043011,1.698842,[],SPEAKER_02,0.9385,False,False
5,12.66,13.66,OTHER_SPEAKER_4,Wat bedoel je?,-0.33186,0.043011,1.698842,[],SPEAKER_04,0.9859,False,False
6,13.78,14.74,OTHER_SPEAKER_3,"Gewoon, toch?",-0.33186,0.043011,1.698842,[],SPEAKER_01,1.0000,False,False
7,14.86,17.22,OTHER_SPEAKER_4,Dat heeft invloed op onze vriendschap.,-0.33186,0.043011,1.698842,[],SPEAKER_04,1.0000,False,False
8,17.34,20.54,OTHER_SPEAKER_3,"Als ik zeg dat ik homo ben, dan ga je niet mee...",-0.33186,0.043011,1.698842,[],SPEAKER_01,1.0000,False,False
9,20.66,22.82,OTHER_SPEAKER_3,"Dan komt het wel op neer, ja.",-0.33186,0.043011,1.698842,[],SPEAKER_01,0.9516,False,True
10,22.94,25.14,OTHER_SPEAKER_3,Wat is er met me huis geweest?,-0.33186,0.043011,1.698842,[],SPEAKER_01,0.9909,False,False
11,25.26,27.82,OTHER_SPEAKER_2,"Als jij nu zegt dat je homo bent, dan gaan men...",-0.33186,0.043011,1.698842,[],SPEAKER_03,1.0000,False,False
12,28.14,31.22,OTHER_SPEAKER_2,"Omdat ik met jou nu, Safi, zeg nu, ik ben met ...",-0.63234,0.054117,1.726804,[],SPEAKER_03,1.0000,False,False
13,31.34,32.34,OTHER_SPEAKER_1,Kere!,-0.63234,0.054117,1.726804,[],SPEAKER_00,0.8796,False,False
14,32.46,33.46,OTHER_SPEAKER_1,Kere!,-0.63234,0.054117,1.726804,[],SPEAKER_00,0.5000,True,True
15,33.58,35.94,OTHER_SPEAKER_1,Dat krijgen we dan nooit doen!,-0.63234,0.054117,1.726804,[],SPEAKER_00,0.5000,True,True
16,36.06,38.10,OTHER_SPEAKER_1,"Maar dat ligt gewoon aan jou, niet aan die men...",-0.63234,0.054117,1.726804,[],SPEAKER_00,1.0000,False,False
17,38.22,40.74,OTHER_SPEAKER_1,"Nee, dan ligt het op dat moment aan jou, want ...",-0.63234,0.054117,1.726804,[],SPEAKER_00,0.8747,False,False
18,40.86,42.82,MAIN_SPEAKER,"Dat ligt gewoon aan jou, want jij bent dan homo.",-0.63234,0.054117,1.726804,[],SPEAKER_02,0.5703,True,False
19,42.94,44.98,MAIN_SPEAKER,"Wacht even, wat is er aan de hand?",-0.63234,0.054117,1.726804,[],SPEAKER_02,1.0000,False,False
20,45.10,46.10,MAIN_SPEAKER,Hoe is het een facky...,-0.63234,0.054117,1.726804,[],SPEAKER_02,0.7463,True,False

### 4.1.1. Conclusie transcriptie

Ook in dit complexere fragment blijft de hoofdinhoud van het gesprek grotendeels herkenbaar. Whisper registreert de belangrijkste uitspraken en de globale ontwikkeling van het gesprek correct. Bij rumoer, overlap en snel wisselende sprekers ontstaan echter duidelijk meer fouten en moeilijk interpreteerbare tekst.  
Dit fragment laat zien dat Whisper Medium voldoende context kan behouden voor globale analyse, maar dat afzonderlijke uitspraken in chaotische passages niet zonder meer als betrouwbaar mogen worden beschouwd. Voor didactische analyse kunnen duidelijke docentinterventies wel worden gebruikt, terwijl details uit overlappende leerlinggesprekken voorzichtiger geïnterpreteerd moeten worden.

## 4.2. Sprekerdiarisatie-evaluatie

In [9]:
show_diarization_comparison(
    df3,
    manual3,
    start_time=0,
    end_time=45
)

,start,end,speaker,text,speaker_confidence,overlap,uncertain_assignment
0,0.8,3.3,MAIN_SPEAKER,"Oswaldo is jouw beste vriend, hè? Of niet?",1.00,False,False
1,3.4,4.4,MAIN_SPEAKER,"Hier in de klas, ja.",1.00,False,False
2,4.5,9.0,MAIN_SPEAKER,Stel je nou voor dat Oswaldo homo is.,1.00,False,False
3,9.1,10.8,MAIN_SPEAKER,Zou dat invloed hebben op je vriendschap?,1.00,False,False
4,10.9,12.5,MAIN_SPEAKER,Jazeker. Dat zou wel invloed hebben.,0.94,False,False
5,12.7,13.7,OTHER_SPEAKER_4,Wat bedoel je?,0.99,False,False
6,13.8,14.7,OTHER_SPEAKER_3,"Gewoon, toch?",1.00,False,False
7,14.9,17.2,OTHER_SPEAKER_4,Dat heeft invloed op onze vriendschap.,1.00,False,False
8,17.3,20.5,OTHER_SPEAKER_3,"Als ik zeg dat ik homo ben, dan ga je niet mee...",1.00,False,False
9,20.7,22.8,OTHER_SPEAKER_3,"Dan komt het wel op neer, ja.",0.95,False,True
10,22.9,25.1,OTHER_SPEAKER_3,Wat is er met me huis geweest?,0.99,False,False
11,25.3,27.8,OTHER_SPEAKER_2,"Als jij nu zegt dat je homo bent, dan gaan men...",1.00,False,False
12,28.1,31.2,OTHER_SPEAKER_2,"Omdat ik met jou nu, Safi, zeg nu, ik ben met ...",1.00,False,False
13,31.3,32.3,OTHER_SPEAKER_1,Kere!,0.88,False,False
14,32.5,33.5,OTHER_SPEAKER_1,Kere!,0.50,True,True
15,33.6,35.9,OTHER_SPEAKER_1,Dat krijgen we dan nooit doen!,0.50,True,True
16,36.1,38.1,OTHER_SPEAKER_1,"Maar dat ligt gewoon aan jou, niet aan die men...",1.00,False,False
17,38.2,40.7,OTHER_SPEAKER_1,"Nee, dan ligt het op dat moment aan jou, want ...",0.87,False,False
18,40.9,42.8,MAIN_SPEAKER,"Dat ligt gewoon aan jou, want jij bent dan homo.",0.57,True,False
19,42.9,45.0,MAIN_SPEAKER,"Wacht even, wat is er aan de hand?",1.00,False,False

,start,end,speaker,text,avg_logprob,no_speech_prob,compression_ratio,quality_flags,speaker_raw,speaker_confidence,overlap,uncertain_assignment
0,0.82,3.26,MAIN_SPEAKER,"Oswaldo is jouw beste vriend, hè? Of niet?",-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
1,3.38,4.38,MAIN_SPEAKER,"Hier in de klas, ja.",-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
2,4.50,8.98,MAIN_SPEAKER,Stel je nou voor dat Oswaldo homo is.,-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
3,9.10,10.82,MAIN_SPEAKER,Zou dat invloed hebben op je vriendschap?,-0.33186,0.043011,1.698842,[],SPEAKER_02,1.0000,False,False
4,10.94,12.54,MAIN_SPEAKER,Jazeker. Dat zou wel invloed hebben.,-0.33186,0.043011,1.698842,[],SPEAKER_02,0.9385,False,False
5,12.66,13.66,OTHER_SPEAKER_4,Wat bedoel je?,-0.33186,0.043011,1.698842,[],SPEAKER_04,0.9859,False,False
6,13.78,14.74,OTHER_SPEAKER_3,"Gewoon, toch?",-0.33186,0.043011,1.698842,[],SPEAKER_01,1.0000,False,False
7,14.86,17.22,OTHER_SPEAKER_4,Dat heeft invloed op onze vriendschap.,-0.33186,0.043011,1.698842,[],SPEAKER_04,1.0000,False,False
8,17.34,20.54,OTHER_SPEAKER_3,"Als ik zeg dat ik homo ben, dan ga je niet mee...",-0.33186,0.043011,1.698842,[],SPEAKER_01,1.0000,False,False
9,20.66,22.82,OTHER_SPEAKER_3,"Dan komt het wel op neer, ja.",-0.33186,0.043011,1.698842,[],SPEAKER_01,0.9516,False,True
10,22.94,25.14,OTHER_SPEAKER_3,Wat is er met me huis geweest?,-0.33186,0.043011,1.698842,[],SPEAKER_01,0.9909,False,False
11,25.26,27.82,OTHER_SPEAKER_2,"Als jij nu zegt dat je homo bent, dan gaan men...",-0.33186,0.043011,1.698842,[],SPEAKER_03,1.0000,False,False
12,28.14,31.22,OTHER_SPEAKER_2,"Omdat ik met jou nu, Safi, zeg nu, ik ben met ...",-0.63234,0.054117,1.726804,[],SPEAKER_03,1.0000,False,False
13,31.34,32.34,OTHER_SPEAKER_1,Kere!,-0.63234,0.054117,1.726804,[],SPEAKER_00,0.8796,False,False
14,32.46,33.46,OTHER_SPEAKER_1,Kere!,-0.63234,0.054117,1.726804,[],SPEAKER_00,0.5000,True,True
15,33.58,35.94,OTHER_SPEAKER_1,Dat krijgen we dan nooit doen!,-0.63234,0.054117,1.726804,[],SPEAKER_00,0.5000,True,True
16,36.06,38.10,OTHER_SPEAKER_1,"Maar dat ligt gewoon aan jou, niet aan die men...",-0.63234,0.054117,1.726804,[],SPEAKER_00,1.0000,False,False
17,38.22,40.74,OTHER_SPEAKER_1,"Nee, dan ligt het op dat moment aan jou, want ...",-0.63234,0.054117,1.726804,[],SPEAKER_00,0.8747,False,False
18,40.86,42.82,MAIN_SPEAKER,"Dat ligt gewoon aan jou, want jij bent dan homo.",-0.63234,0.054117,1.726804,[],SPEAKER_02,0.5703,True,False
19,42.94,44.98,MAIN_SPEAKER,"Wacht even, wat is er aan de hand?",-0.63234,0.054117,1.726804,[],SPEAKER_02,1.0000,False,False

### 4.2.1. Sprekerdiarisatie conclusie

In dit fragment onderscheidt de diarization meerdere sprekers en werkt deze daardoor beter dan in fragment 2. De globale sprekerstructuur van het gesprek wordt zichtbaar, maar door overlap, rumoer en snelle wisselingen blijven sommige labels onzeker.  
De diarization lijkt daarmee bruikbaar als ondersteunende context, maar niet als foutloze bron voor exacte sprekeridentificatie. Vooral bij overlappende spraak en korte uitingen moet rekening worden gehouden met verkeerde of onzekere toewijzingen.

## 5. Eindconclusie

De tests laten zien dat Whisper Medium voorlopig voldoende transcriptkwaliteit levert voor verdere ontwikkeling van de workshopcoach. In alle drie de fragmenten blijft de belangrijkste inhoud van gesprekken grotendeels behouden, ook wanneer sprake is van rumoer of meerdere sprekers. De kwaliteit neemt af bij overlap en chaotische gesprekken, maar docentvragen, uitleg en langere interventies blijven meestal herkenbaar. 
De grootste onzekerheid zit op dit moment niet in de algemene transcriptiekwaliteit, maar in de sprekerverdeling. Korte docent- en leerlingreacties kunnen binnen één Whisper-segment terechtkomen, waardoor één sprekerlabel aan tekst van meerdere personen wordt gekoppeld. Daarnaast laat fragment 2 zien dat diarization in sommige situaties vrijwel alle spraak aan de hoofdspreker kan toewijzen.

Voor de beoogde analyse betekent dit dat de pipeline voorlopig geschikt lijkt voor indicatoren die vooral gebaseerd zijn op duidelijke en langere docentuitspraken, zoals vraaggedrag, uitleg en expliciete controles op begrip. Indicatoren die sterk afhankelijk zijn van exacte beurtwisseling of korte leerlingreacties zijn gevoeliger voor fouten.
Op basis van deze tests is er op dit moment geen aanleiding om de transcriptiepipeline verder te optimaliseren voordat de eerste classificatie-experimenten zijn uitgevoerd. De gevonden beperkingen worden vastgelegd en kunnen opnieuw worden onderzocht wanneer blijkt dat ze de didactische classificatie daadwerkelijk belemmeren.