# <b> Problemen bij stemherkenning en diarisatie oplossen: overlap </b>

## Testaudio6 — unseen validation fragment

Doel:
controleren hoe de huidige diarization + docent recognition-pipeline werkt op nieuw audiofragment met dezelfde docentstem.

Bron:
Peter Hoefnagels-fragment, nog niet gebruikt bij eerdere test.

Belangrijk:
dit fragment wordt gebruikt als unseen test en niet om de threshold op te tunen.

In [1]:
import json
import pandas as pd
from pathlib import Path

path = Path("../../Data-local/processed/docent_recognition/testaudio6_fragment_diarized_turns_docent_roles_BEFORE.json")

with open(path, encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame([
    {
        "turn_id": t["turn_id"],
        "start": t["start"],
        "end": t["end"],
        "speaker": t["speaker"],
        "text": t["text"],
        "overlap": t["overlap"],
        "uncertain": t["uncertain_assignment"],
        "docent_role": t["docent_role"],
        "similarity": t["docent_role_similarity"],
    }
    for t in data["turns"]
])

df

,turn_id,start,end,speaker,text,overlap,uncertain,docent_role,similarity
0,0,0.00,2.60,MAIN_SPEAKER,Het gaat erom dat we mannen niet nodig hebben.,False,False,OTHER,0.2062
1,1,2.60,4.60,OTHER_SPEAKER_1,Wij zijn overbodig geworden in Maatschappij.,True,False,ONZEKER,NaN
2,2,4.60,5.60,OTHER_SPEAKER_1,"Ja, helemaal.",True,False,ONZEKER,NaN
3,3,5.60,6.60,OTHER_SPEAKER_1,Is dat serieus?,True,True,ONZEKER,NaN
4,4,6.60,13.16,MAIN_SPEAKER,Serieus. Want vroeger was het misschien nog zo...,False,False,OTHER,0.2246
5,5,13.16,15.16,OTHER_SPEAKER_1,Maar nu heb je een navigatiesysteem.,True,False,ONZEKER,NaN
6,6,15.16,16.16,MAIN_SPEAKER,Precies.,True,True,ONZEKER,NaN
7,7,16.16,17.16,MAIN_SPEAKER,Precies.,False,False,OTHER,0.1730
8,8,17.16,18.16,OTHER_SPEAKER_1,"Nee, maar u begrijpt het toch?",True,True,ONZEKER,NaN
9,9,18.16,19.16,OTHER_SPEAKER_1,We hebben onszelf eigenlijk een beetje...,False,False,DOCENT,0.3547
10,10,19.16,20.16,OTHER_SPEAKER_1,Nou ja.,True,False,ONZEKER,NaN
11,11,20.16,22.16,OTHER_SPEAKER_1,"Nou, ik begrijp het niet, want ik vind het een...",True,False,ONZEKER,NaN
12,12,22.16,23.16,MAIN_SPEAKER,Maar u zegt het zelf!,True,False,ONZEKER,NaN
13,13,23.16,24.16,MAIN_SPEAKER,U zegt het zelf!,True,False,ONZEKER,NaN
14,14,24.16,25.16,MAIN_SPEAKER,"Ja, nee, ja.",False,True,ONZEKER,NaN
15,15,25.16,26.16,OTHER_SPEAKER_1,Als grapje gewoon.,False,False,OTHER,0.3067
16,16,26.16,27.16,OTHER_SPEAKER_1,Niet als...,True,False,ONZEKER,NaN
17,17,27.16,28.16,OTHER_SPEAKER_1,"Nee, het is geen grapje.",True,False,ONZEKER,NaN
18,18,28.16,29.16,MAIN_SPEAKER,Het is toch gewoon waar.,True,False,ONZEKER,NaN
19,19,29.32,33.32,MAIN_SPEAKER,"Oké, dus waar hebben we mannen dan voor nodig?",True,False,ONZEKER,NaN
20,20,33.32,34.32,MAIN_SPEAKER,Klusjes in huis?,False,False,OTHER,0.2571
21,21,34.32,35.32,MAIN_SPEAKER,Ja.,True,False,ONZEKER,NaN
22,22,35.32,36.32,MAIN_SPEAKER,"Nee, ook niet.",True,False,ONZEKER,NaN
23,23,36.32,37.32,MAIN_SPEAKER,"Niets, wat?",True,False,ONZEKER,NaN
24,24,37.32,42.24,MAIN_SPEAKER,"Nee, maar we hebben gewoon tutorials op YouTub...",False,False,OTHER,0.1498
25,25,42.24,43.80,MAIN_SPEAKER,"Dus nee, ik heb geen man meer nodig.",True,False,ONZEKER,NaN
26,26,43.80,48.40,OTHER_SPEAKER_1,De man is in eerste instantie ook om de vrouw ...,False,False,DOCENT,0.3783
27,27,48.40,49.40,OTHER_SPEAKER_1,Dat is eigenlijk ook de man.,True,True,ONZEKER,NaN
28,28,49.40,51.40,MAIN_SPEAKER,Maar waarom kan een vrouw dat niet uit zichzel...,False,False,OTHER,0.2568
29,29,51.40,52.40,OTHER_SPEAKER_1,Ja...,False,True,ONZEKER,NaN
30,30,52.40,55.40,MAIN_SPEAKER,Waarom heb ik daar een man voor nodig?,False,True,ONZEKER,NaN
31,31,55.40,56.40,OTHER_SPEAKER_1,Maar echt serieus?,False,True,ONZEKER,NaN
32,32,56.40,57.40,OTHER_SPEAKER_1,"Ja, ik heb...",True,False,ONZEKER,NaN
33,33,57.40,74.48,MAIN_SPEAKER,"Nee, serieus. Ik heb gewoon genoeg aan mezelf,...",False,False,OTHER,0.2137
34,34,74.48,76.92,OTHER_SPEAKER_1,Nee.,False,True,ONZEKER,NaN
35,35,76.92,77.92,OTHER_SPEAKER_1,Ja?,False,True,ONZEKER,NaN
36,36,77.92,78.92,OTHER_SPEAKER_1,Is het een soort...,False,False,OTHER,0.2500
37,37,78.92,82.72,OTHER_SPEAKER_1,"Vind je het meer, vrouw, dat de man overbodig is?",True,False,ONZEKER,NaN
38,38,82.72,83.72,OTHER_SPEAKER_1,Ik denk...,False,True,ONZEKER,NaN

In [3]:
df["docent_role"].value_counts()

docent_role
ONZEKER    28
OTHER       9
DOCENT      2
Name: count, dtype: int64

### Observatie

Bij testaudio6 worden opvallend veel turns als ONZEKER gemarkeerd.
Dit komt vooral doordat `overlap=true` in de huidige docent recognition-logica
direct leidt tot ONZEKER, zonder dat speaker recognition wordt uitgevoerd.

Handmatige controle van het audiofragment laat zien dat niet alle overlap-turns
daadwerkelijk onbruikbare gemengde spraak bevatten.

Daarom wordt getest of `overlap` beter als waarschuwing behandeld in plaats van een strenge regel. Dit wordt aangepast in de code. 
Overlap is dus voor nu nog te streng gedefinieerd.

### Opnieuw testen na aanpassing

Nieuwe regel:
- `uncertain_assignment=true` → ONZEKER
- overlap alleen → speaker recognition mag doorgaan
- overlap wordt wel als waarschuwing bewaard

In [4]:
path = Path("../../Data-local/processed/docent_recognition/testaudio6_fragment_diarized_turns_docent_roles.json")

with open(path, encoding="utf-8") as f:
    data = json.load(f)

df2 = pd.DataFrame([
    {
        "turn_id": t["turn_id"],
        "start": t["start"],
        "end": t["end"],
        "speaker": t["speaker"],
        "text": t["text"],
        "overlap": t["overlap"],
        "uncertain": t["uncertain_assignment"],
        "docent_role": t["docent_role"],
        "similarity": t["docent_role_similarity"],
    }
    for t in data["turns"]
])

df2

,turn_id,start,end,speaker,text,overlap,uncertain,docent_role,similarity
0,0,0.00,2.60,MAIN_SPEAKER,Het gaat erom dat we mannen niet nodig hebben.,False,False,OTHER,0.2062
1,1,2.60,4.60,OTHER_SPEAKER_1,Wij zijn overbodig geworden in Maatschappij.,True,False,DOCENT,0.4216
2,2,4.60,5.60,OTHER_SPEAKER_1,"Ja, helemaal.",True,False,OTHER,0.0925
3,3,5.60,6.60,OTHER_SPEAKER_1,Is dat serieus?,True,True,ONZEKER,NaN
4,4,6.60,13.16,MAIN_SPEAKER,Serieus. Want vroeger was het misschien nog zo...,False,False,OTHER,0.2246
5,5,13.16,15.16,OTHER_SPEAKER_1,Maar nu heb je een navigatiesysteem.,True,False,DOCENT,0.3639
6,6,15.16,16.16,MAIN_SPEAKER,Precies.,True,True,ONZEKER,NaN
7,7,16.16,17.16,MAIN_SPEAKER,Precies.,False,False,OTHER,0.1730
8,8,17.16,18.16,OTHER_SPEAKER_1,"Nee, maar u begrijpt het toch?",True,True,ONZEKER,NaN
9,9,18.16,19.16,OTHER_SPEAKER_1,We hebben onszelf eigenlijk een beetje...,False,False,DOCENT,0.3547
10,10,19.16,20.16,OTHER_SPEAKER_1,Nou ja.,True,False,OTHER,0.0775
11,11,20.16,22.16,OTHER_SPEAKER_1,"Nou, ik begrijp het niet, want ik vind het een...",True,False,OTHER,0.2399
12,12,22.16,23.16,MAIN_SPEAKER,Maar u zegt het zelf!,True,False,OTHER,0.1830
13,13,23.16,24.16,MAIN_SPEAKER,U zegt het zelf!,True,False,OTHER,0.1374
14,14,24.16,25.16,MAIN_SPEAKER,"Ja, nee, ja.",False,True,ONZEKER,NaN
15,15,25.16,26.16,OTHER_SPEAKER_1,Als grapje gewoon.,False,False,OTHER,0.3067
16,16,26.16,27.16,OTHER_SPEAKER_1,Niet als...,True,False,OTHER,0.1289
17,17,27.16,28.16,OTHER_SPEAKER_1,"Nee, het is geen grapje.",True,False,OTHER,0.0599
18,18,28.16,29.16,MAIN_SPEAKER,Het is toch gewoon waar.,True,False,OTHER,0.0205
19,19,29.32,33.32,MAIN_SPEAKER,"Oké, dus waar hebben we mannen dan voor nodig?",True,False,OTHER,0.1750
20,20,33.32,34.32,MAIN_SPEAKER,Klusjes in huis?,False,False,OTHER,0.2571
21,21,34.32,35.32,MAIN_SPEAKER,Ja.,True,False,OTHER,0.1091
22,22,35.32,36.32,MAIN_SPEAKER,"Nee, ook niet.",True,False,OTHER,-0.0103
23,23,36.32,37.32,MAIN_SPEAKER,"Niets, wat?",True,False,OTHER,-0.0621
24,24,37.32,42.24,MAIN_SPEAKER,"Nee, maar we hebben gewoon tutorials op YouTub...",False,False,OTHER,0.1498
25,25,42.24,43.80,MAIN_SPEAKER,"Dus nee, ik heb geen man meer nodig.",True,False,OTHER,0.1333
26,26,43.80,48.40,OTHER_SPEAKER_1,De man is in eerste instantie ook om de vrouw ...,False,False,DOCENT,0.3783
27,27,48.40,49.40,OTHER_SPEAKER_1,Dat is eigenlijk ook de man.,True,True,ONZEKER,NaN
28,28,49.40,51.40,MAIN_SPEAKER,Maar waarom kan een vrouw dat niet uit zichzel...,False,False,OTHER,0.2568
29,29,51.40,52.40,OTHER_SPEAKER_1,Ja...,False,True,ONZEKER,NaN
30,30,52.40,55.40,MAIN_SPEAKER,Waarom heb ik daar een man voor nodig?,False,True,ONZEKER,NaN
31,31,55.40,56.40,OTHER_SPEAKER_1,Maar echt serieus?,False,True,ONZEKER,NaN
32,32,56.40,57.40,OTHER_SPEAKER_1,"Ja, ik heb...",True,False,OTHER,0.1907
33,33,57.40,74.48,MAIN_SPEAKER,"Nee, serieus. Ik heb gewoon genoeg aan mezelf,...",False,False,OTHER,0.2137
34,34,74.48,76.92,OTHER_SPEAKER_1,Nee.,False,True,ONZEKER,NaN
35,35,76.92,77.92,OTHER_SPEAKER_1,Ja?,False,True,ONZEKER,NaN
36,36,77.92,78.92,OTHER_SPEAKER_1,Is het een soort...,False,False,OTHER,0.2500
37,37,78.92,82.72,OTHER_SPEAKER_1,"Vind je het meer, vrouw, dat de man overbodig is?",True,False,DOCENT,0.3669
38,38,82.72,83.72,OTHER_SPEAKER_1,Ik denk...,False,True,ONZEKER,NaN

#### Voor aanpassing overlap regel

In [6]:
df["docent_role"].value_counts()

docent_role
ONZEKER    28
OTHER       9
DOCENT      2
Name: count, dtype: int64

#### Na aanpassing overlap regel

In [5]:
df2["docent_role"].value_counts()

docent_role
OTHER      23
ONZEKER    11
DOCENT      5
Name: count, dtype: int64

De oorspronkelijke overlap-regel bleek te conservatief. Na aanpassing daalde het aantal ONZEKER-labels van 28 naar 11, terwijl onzeker toegewezen turns geblokkeerd bleven.

## Testaudio7 — sanity validation fragment

Als laatste check wordt er een fragment gebruikt van Peter Hoefnagels waar er veel sprake is van overlap.

In [9]:
path = Path("../../Data-local/processed/docent_recognition/testaudio7_fragment_diarized_turns_docent_roles.json")

with open(path, encoding="utf-8") as f:
    data = json.load(f)

df3 = pd.DataFrame([
    {
        "turn_id": t["turn_id"],
        "start": t["start"],
        "end": t["end"],
        "speaker": t["speaker"],
        "text": t["text"],
        "overlap": t["overlap"],
        "uncertain": t["uncertain_assignment"],
        "docent_role": t["docent_role"],
        "similarity": t["docent_role_similarity"],
    }
    for t in data["turns"]
])

df3

,turn_id,start,end,speaker,text,overlap,uncertain,docent_role,similarity
0,0,0.0,3.0,MAIN_SPEAKER,"Ja, dames en heren, mag ik de aantal, wat heb ...",False,False,DOCENT,0.4449
1,1,3.0,4.0,MAIN_SPEAKER,Heb je de cijfers?,False,True,ONZEKER,NaN
2,2,4.0,6.0,OTHER_SPEAKER_1,"Ja, meneer, dat doet u wel heel lang.",True,False,OTHER,0.0445
3,3,6.0,7.0,OTHER_SPEAKER_1,"Nee, helemaal niets.",True,True,ONZEKER,NaN
4,4,7.0,9.0,OTHER_SPEAKER_1,U heeft twee weken erover gedaan.,True,False,OTHER,0.3428
5,5,9.0,12.0,MAIN_SPEAKER,"Guus, echt serieus, echt niet waar wat je zegt.",True,True,ONZEKER,NaN
6,6,12.0,20.0,MAIN_SPEAKER,Waarom zeg je dingen die niet waar zijn? Vorig...,False,False,DOCENT,0.5260
7,7,20.0,22.0,OTHER_SPEAKER_1,"Nou, die wiskundige leraar doet altijd binnen ...",True,False,OTHER,-0.0018
8,8,22.0,23.0,OTHER_SPEAKER_1,Ja.,False,False,OTHER,0.0547
9,9,23.0,24.0,OTHER_SPEAKER_1,"Nee, dat is onzin.",True,True,ONZEKER,NaN
10,10,24.0,25.0,MAIN_SPEAKER,Echt wel.,True,False,OTHER,0.2087
11,11,25.0,26.0,MAIN_SPEAKER,"Nee, maar die hebben nog geen leven.",True,False,OTHER,0.2761
12,12,26.0,28.0,MAIN_SPEAKER,"Ja, nou, u wel een leven.",True,True,ONZEKER,NaN
13,13,28.0,29.0,MAIN_SPEAKER,Ik heb wel een leven.,True,False,OTHER,0.2409
14,14,29.0,34.0,MAIN_SPEAKER,"Maar ik heb het binnen een week, heb ik het na...",False,False,DOCENT,0.4964
15,15,34.0,35.0,MAIN_SPEAKER,Nee.,False,True,ONZEKER,NaN
16,16,35.0,36.0,MAIN_SPEAKER,"Nee, ik vind het jammer.",True,False,OTHER,0.1955
17,17,36.0,37.0,MAIN_SPEAKER,Hoeveel voldoende zijn er?,True,False,OTHER,0.2102
18,18,37.0,39.0,MAIN_SPEAKER,Volgens mij hadden we heel goed geoefend.,True,False,OTHER,0.2754
19,19,39.0,47.0,MAIN_SPEAKER,"Hoeveel voldoende zijn er? Ja, niet veel. Ik g...",False,False,DOCENT,0.4161
20,20,47.0,48.0,OTHER_SPEAKER_1,Twee zeker.,False,False,OTHER,0.0353
21,21,48.0,49.0,MAIN_SPEAKER,Twee?,False,True,ONZEKER,NaN
22,22,49.0,50.0,MAIN_SPEAKER,Ja.,True,True,ONZEKER,NaN
23,23,50.0,59.0,MAIN_SPEAKER,Jij begint voortvarend. Maar het is geen twee....,False,False,DOCENT,0.5054
24,24,59.0,60.0,None,Nee.,False,True,ONZEKER,NaN
25,25,60.0,62.0,MAIN_SPEAKER,Wat heb je over je schunde?,False,False,OTHER,0.2381

In [10]:
df3["docent_role"].value_counts()

docent_role
OTHER      12
ONZEKER     9
DOCENT      5
Name: count, dtype: int64

De onzekerheidsgraad zit hier wel iets hoger dan bij de vorige fragmenten. Dit fragment specifiek heeft ook wel een erg rumoerige klas en veel leerlingen die door de docent praten. Hier moet rekening mee gehouden worden voor het model.